#!/usr/bin/env python
# this could be more sophisticated for
# a variety of real programming languages,
# but is mostly sufficient as stands for config
# files
import sys
for line in sys.stdin.readlines():
    pos = line.find("#")
    if pos >= 0:
        print line[0:pos]
    else:
        print line,
